# Generated by Django 4.2 on 2023-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_newsarticle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='end_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='impact',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='intensity',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='likelihood',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='relevance',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='start_year',
            field=models.IntegerField(default=None),
        ),
    ]
