# Generated by Django 4.2 on 2023-11-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_newsarticle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.CharField(max_length=512),
        ),
    ]
